name = "boi-gordo-investimentos"
main = "src/index.js"
compatibility_date = "2023-05-18"

[build]
command = "echo 'No build required for this setup'"
cwd = "."
watch_dir = ["src", "public"]

[[env.production.d1_databases]]
binding = "DB" 
database_name = "boi_gordo_db"
database_id = ""

[[env.development.d1_databases]]
binding = "DB"
database_name = "boi_gordo_db"
database_id = "local-development-db"

[vars]
DATABASE_ID = "local-development-db"

# Servir arquivos estáticos da pasta public
[site]
bucket = "./public"
